// flow-typed signature: 1170f89ef470aa211cd50d4bb82c9b23
// flow-typed version: <<STUB>>/passport-cas_v^0.1.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-cas'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-cas' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'passport-cas/index' {
  declare module.exports: $Exports<'passport-cas'>;
}
declare module 'passport-cas/index.js' {
  declare module.exports: $Exports<'passport-cas'>;
}
