version: '2'
services:
  postgres:
    image: postgres
    environment:
        - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./test-seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
